name: Run hockey.py daily

# Schemalägg att köra varje dag kl. 20:45 UTC
on:
  schedule:
    - cron: '00 20 * * *'  # Kör varje dag kl. 20:45 UTC

jobs:
  run-script:
    runs-on: ubuntu-latest  # Använder den senaste versionen av Ubuntu

    steps:
    # Checka ut koden från din repo
    - name: Checkout repository
      uses: actions/checkout@v2

    # Installera Python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Välj din Python-version (t.ex. 3.9)

    # Installera nödvändiga beroenden (om det behövs, du kan lägga till fler beroenden här)
    - name: Install dependencies
      run: |
        pip install requests mechanicalsoup beautifulsoup4

    # Kör ditt skript
    - name: Run hockey script
      run: python hockey.py
